import { NextResponse } from "next/server";
import { withAdmin } from "@/lib/api-auth";
import { logAudit, auditContext } from "@/lib/audit";
import { checkBodySize } from "@/lib/body-size";
import { checkRateLimit } from "@/lib/rate-limit";
import {
  processBackupImport,
  MAX_CIPHERTEXT_BYTES,
} from "@/lib/backup-import";
import {
  startSession,
  appendChunk,
  getSessionStream,
  clearSession,
} from "@/lib/import-session";
import { translatorForRequest } from "@/lib/i18n/server-locale";
import { localizeBackupMessage } from "@/lib/backup-messages";
import type { Translator } from "@/lib/i18n/translate";

// Per-chunk size cap, the same as the sibling /api/setup/import-chunk route.
// Without it, one huge chunk could run the server out of memory (OOM) while
// req.arrayBuffer() reads it in.
const MAX_CHUNK_BYTES = 32 * 1024 * 1024;

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const MIN_BACKUP_PASSWORD_LEN = 12;

function passwordOrError(t: Translator): { password: string } | NextResponse {
  const password = process.env.BACKUP_DB_PASSWORD ?? "";
  if (password.length === 0) {
    return NextResponse.json(
      { error: t("apiAdmin.backup.notConfigured") },
      { status: 503 },
    );
  }
  if (password.length < MIN_BACKUP_PASSWORD_LEN) {
    return NextResponse.json(
      { error: t("apiAdmin.backup.passwordTooShort", { min: MIN_BACKUP_PASSWORD_LEN }) },
      { status: 503 },
    );
  }
  return { password };
}

// POST: append a chunk. Final chunk runs the import.
//
// Headers (matches /api/setup/import-chunk):
//   X-Upload-Id     UUID v4 generated by the client
//   X-Chunk-Index   0-based index of this chunk
//   X-Chunk-Total   total chunks
//   X-File-Size     total file size in bytes
export const POST = withAdmin(async (req, _ctx, session) => {
  const t = translatorForRequest(req);
  const pw = passwordOrError(t);
  if (pw instanceof NextResponse) return pw;
  const { password } = pw;

  const uploadId = req.headers.get("x-upload-id") ?? "";
  const chunkIndex = Number(req.headers.get("x-chunk-index") ?? "");
  const chunkTotal = Number(req.headers.get("x-chunk-total") ?? "");
  const fileSize = Number(req.headers.get("x-file-size") ?? "");

  if (!uploadId || !Number.isFinite(chunkIndex) || !Number.isFinite(chunkTotal) || !Number.isFinite(fileSize)) {
    return NextResponse.json({ error: t("apiAdmin.backup.invalidUploadHeaders") }, { status: 400 });
  }
  if (fileSize > MAX_CIPHERTEXT_BYTES) {
    return NextResponse.json(
      { error: t("apiAdmin.backup.fileTooLarge", { mb: Math.round(MAX_CIPHERTEXT_BYTES / (1024 * 1024)) }) },
      { status: 413 },
    );
  }

  if (!req.body) {
    return NextResponse.json({ error: t("apiAdmin.backup.emptyChunk") }, { status: 400 });
  }

  // Rate-limit the restore *attempt*, not each chunk: consume one slot when the
  // client opens the session (chunk 0). A real backup is split into many 16 MiB
  // chunks, so a per-chunk limiter would burn the bucket and 429 the restore
  // partway through. Bounds how often a compromised admin can drive the
  // destructive TRUNCATE+INSERT / PBKDF2 import.
  if (chunkIndex === 0 && !checkRateLimit(`admin-db-import:${session.user.id}`, 5, 60 * 60 * 1000)) {
    return NextResponse.json({ error: t("apiAdmin.backup.tooManyRestores") }, { status: 429 });
  }

  // Header-only size check BEFORE claiming the single upload slot. startSession()
  // mkdtemps a temp dir and occupies the one global slot; an oversized chunk 0 that
  // bailed after it would strand that slot (409 for everyone else) until the 30-min TTL.
  const sizeCheck = checkBodySize(req, MAX_CHUNK_BYTES);
  if (sizeCheck) return sizeCheck;

  if (chunkIndex === 0) {
    const start = await startSession({ uploadId, totalSize: fileSize, totalChunks: chunkTotal });
    if (!start.ok) {
      const e = start.error;
      if (e.kind === "in-progress") {
        return NextResponse.json(
          { error: t("apiAdmin.backup.uploadInProgress") },
          { status: 409 },
        );
      }
      if (e.kind === "size-too-large") {
        return NextResponse.json(
          { error: t("apiAdmin.backup.fileTooLarge", { mb: Math.round(e.max / (1024 * 1024)) }) },
          { status: 413 },
        );
      }
      return NextResponse.json({ error: t("apiAdmin.backup.invalidUploadParams") }, { status: 400 });
    }
  }

  const chunkBytes = new Uint8Array(await req.arrayBuffer());
  if (chunkBytes.byteLength > MAX_CHUNK_BYTES) {
    // Belt-and-suspenders for transfer-encoding: chunked uploads where the
    // Content-Length-based check above can't trigger. An oversized chunk corrupts
    // the upload, so release the slot for ANY index (not just chunk 0) — otherwise
    // an oversized non-zero chunk strands the global slot until its TTL.
    await clearSession(uploadId);
    return NextResponse.json(
      { error: t("apiAdmin.backup.chunkTooLarge", { mb: Math.round(MAX_CHUNK_BYTES / (1024 * 1024)) }) },
      { status: 413 },
    );
  }
  const append = await appendChunk(uploadId, chunkIndex, chunkBytes);
  if (!append.ok) {
    const e = append.error;
    if (e.kind === "no-session") {
      return NextResponse.json({ error: t("apiAdmin.backup.noUploadSession") }, { status: 409 });
    }
    if (e.kind === "session-mismatch") {
      return NextResponse.json({ error: t("apiAdmin.backup.uploadIdMismatch") }, { status: 409 });
    }
    if (e.kind === "expired") {
      return NextResponse.json({ error: t("apiAdmin.backup.uploadExpired") }, { status: 410 });
    }
    if (e.kind === "out-of-order") {
      return NextResponse.json({ error: t("apiAdmin.backup.outOfOrder", { expected: e.expected }) }, { status: 409 });
    }
    if (e.kind === "size-mismatch") {
      return NextResponse.json(
        { error: t("apiAdmin.backup.incomplete", { received: e.received, expected: e.expected }) },
        { status: 400 },
      );
    }
    return NextResponse.json({ error: t("apiAdmin.backup.chunkExceedsDeclared") }, { status: 413 });
  }

  if (!append.complete) {
    return NextResponse.json({
      ok: true,
      received: append.received,
      total: append.total,
      bytesWritten: append.bytesWritten,
      complete: false,
    });
  }

  const stream = getSessionStream(uploadId);
  if (!stream) {
    await clearSession(uploadId);
    return NextResponse.json({ error: t("apiAdmin.backup.uploadStateLost") }, { status: 500 });
  }

  let result;
  try {
    result = await processBackupImport(stream, password);
  } finally {
    await clearSession(uploadId);
  }

  if (!result.ok) {
    if (result.errors) {
      return NextResponse.json({
        ok: false,
        complete: true,
        summary: result.summary,
        errors: result.errors,
      });
    }
    return NextResponse.json({ error: localizeBackupMessage(result.error, t), complete: true }, { status: result.status });
  }

  // The DB restore already executed; a failed audit write must not 500 a
  // successful import (GR26). logAudit swallows write failures internally.
  void logAudit({
    userId: session.user.id,
    userName: session.user.name ?? session.user.email,
    action: "BACKUP_IMPORT",
    target: "backup:full-db",
    details: {
      format: "sql",
      encrypted: true,
      mode: "admin-chunked",
      after: {
        totalStatements: result.summary.total,
        executed: result.summary.executed,
        skipped: result.summary.skipped,
        errors: result.summary.errors,
      },
    },
    ...auditContext(req, session),
  });

  return NextResponse.json({
    ok: true,
    complete: true,
    summary: result.summary,
    ...(result.warning ? { warning: result.warning } : {}),
  });
});

// DELETE: cancel the in-flight upload.
export const DELETE = withAdmin(async (req, _ctx, _session) => {
  const t = translatorForRequest(req);
  const uploadId = req.headers.get("x-upload-id") ?? "";
  if (!uploadId) {
    return NextResponse.json({ error: t("apiAdmin.backup.missingUploadId") }, { status: 400 });
  }
  await clearSession(uploadId);
  return NextResponse.json({ ok: true });
});
