import { NextResponse } from "next/server";
import { withAdmin } from "@/lib/api-auth";
import { logAuditOrFail, auditContext } from "@/lib/audit";
import { checkBodySize } from "@/lib/body-size";
import {
  processBackupImport,
  MAX_CIPHERTEXT_BYTES,
} from "@/lib/backup-import";

// Per-chunk hard cap matches the sibling /api/setup/import-chunk route. Without
// this an admin-or-attacker-with-admin-creds could send a single oversized chunk
// and OOM Node before the arrayBuffer() resolved.
const MAX_CHUNK_BYTES = 32 * 1024 * 1024;
import {
  startSession,
  appendChunk,
  getSessionStream,
  clearSession,
} from "@/lib/import-session";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const MIN_BACKUP_PASSWORD_LEN = 12;

function passwordOrError(): { password: string } | NextResponse {
  const password = process.env.BACKUP_DB_PASSWORD ?? "";
  if (password.length === 0) {
    return NextResponse.json(
      { error: "Backup is not configured. Set the BACKUP_DB_PASSWORD environment variable on the server." },
      { status: 503 },
    );
  }
  if (password.length < MIN_BACKUP_PASSWORD_LEN) {
    return NextResponse.json(
      { error: `BACKUP_DB_PASSWORD is too short (minimum ${MIN_BACKUP_PASSWORD_LEN} characters).` },
      { status: 503 },
    );
  }
  return { password };
}

// POST: append a chunk. Final chunk runs the import.
//
// Headers (matches /api/setup/import-chunk):
//   X-Upload-Id     UUID v4 generated by the client
//   X-Chunk-Index   0-based index of this chunk
//   X-Chunk-Total   total chunks
//   X-File-Size     total file size in bytes
export const POST = withAdmin(async (req, _ctx, session) => {
  const pw = passwordOrError();
  if (pw instanceof NextResponse) return pw;
  const { password } = pw;

  const uploadId = req.headers.get("x-upload-id") ?? "";
  const chunkIndex = Number(req.headers.get("x-chunk-index") ?? "");
  const chunkTotal = Number(req.headers.get("x-chunk-total") ?? "");
  const fileSize = Number(req.headers.get("x-file-size") ?? "");

  if (!uploadId || !Number.isFinite(chunkIndex) || !Number.isFinite(chunkTotal) || !Number.isFinite(fileSize)) {
    return NextResponse.json({ error: "Missing or invalid upload headers." }, { status: 400 });
  }
  if (fileSize > MAX_CIPHERTEXT_BYTES) {
    return NextResponse.json(
      { error: `File exceeds the ${Math.round(MAX_CIPHERTEXT_BYTES / (1024 * 1024))} MB limit.` },
      { status: 413 },
    );
  }

  if (!req.body) {
    return NextResponse.json({ error: "Empty chunk body." }, { status: 400 });
  }

  // Header-only size check BEFORE claiming the single upload slot. startSession()
  // mkdtemps a temp dir and occupies the one global slot; an oversized chunk 0 that
  // bailed after it would strand that slot (409 for everyone else) until the 30-min TTL.
  const sizeCheck = checkBodySize(req, MAX_CHUNK_BYTES);
  if (sizeCheck) return sizeCheck;

  if (chunkIndex === 0) {
    const start = await startSession({ uploadId, totalSize: fileSize, totalChunks: chunkTotal });
    if (!start.ok) {
      const e = start.error;
      if (e.kind === "in-progress") {
        return NextResponse.json(
          { error: "Another upload is already in progress. Wait for it to finish or cancel it." },
          { status: 409 },
        );
      }
      if (e.kind === "size-too-large") {
        return NextResponse.json(
          { error: `File exceeds the ${Math.round(e.max / (1024 * 1024))} MB limit.` },
          { status: 413 },
        );
      }
      return NextResponse.json({ error: "Invalid upload parameters." }, { status: 400 });
    }
  }

  const chunkBytes = new Uint8Array(await req.arrayBuffer());
  if (chunkBytes.byteLength > MAX_CHUNK_BYTES) {
    // Belt-and-suspenders for transfer-encoding: chunked uploads where the
    // Content-Length-based check above can't trigger. An oversized chunk corrupts
    // the upload, so release the slot for ANY index (not just chunk 0) — otherwise
    // an oversized non-zero chunk strands the global slot until its TTL.
    await clearSession(uploadId);
    return NextResponse.json(
      { error: `Chunk exceeds ${Math.round(MAX_CHUNK_BYTES / (1024 * 1024))} MB cap.` },
      { status: 413 },
    );
  }
  const append = await appendChunk(uploadId, chunkIndex, chunkBytes);
  if (!append.ok) {
    const e = append.error;
    if (e.kind === "no-session") {
      return NextResponse.json({ error: "No active upload session — start at chunk 0." }, { status: 409 });
    }
    if (e.kind === "session-mismatch") {
      return NextResponse.json({ error: "Upload-id does not match the active session." }, { status: 409 });
    }
    if (e.kind === "expired") {
      return NextResponse.json({ error: "Upload session expired — restart from chunk 0." }, { status: 410 });
    }
    if (e.kind === "out-of-order") {
      return NextResponse.json({ error: `Out-of-order chunk. Next expected index: ${e.expected}.` }, { status: 409 });
    }
    return NextResponse.json({ error: "Chunk exceeds declared file size." }, { status: 413 });
  }

  if (!append.complete) {
    return NextResponse.json({
      ok: true,
      received: append.received,
      total: append.total,
      bytesWritten: append.bytesWritten,
      complete: false,
    });
  }

  const stream = getSessionStream(uploadId);
  if (!stream) {
    await clearSession(uploadId);
    return NextResponse.json({ error: "Upload state lost between final chunk and import." }, { status: 500 });
  }

  let result;
  try {
    result = await processBackupImport(stream, password);
  } finally {
    await clearSession(uploadId);
  }

  if (!result.ok) {
    if (result.errors) {
      return NextResponse.json({
        ok: false,
        complete: true,
        summary: result.summary,
        errors: result.errors,
      });
    }
    return NextResponse.json({ error: result.error, complete: true }, { status: result.status });
  }

  try {
    await logAuditOrFail({
      userId: session.user.id,
      userName: session.user.name ?? session.user.email,
      action: "BACKUP_IMPORT",
      target: "backup:full-db",
      details: {
        format: "sql",
        encrypted: true,
        mode: "admin-chunked",
        after: {
          totalStatements: result.summary.total,
          executed: result.summary.executed,
          skipped: result.summary.skipped,
          errors: result.summary.errors,
        },
      },
      ...auditContext(req, session),
    });
  } catch (err) {
    console.error("[audit] Critical audit log failed:", err);
    return NextResponse.json({ error: "Audit logging failed" }, { status: 500 });
  }

  return NextResponse.json({
    ok: true,
    complete: true,
    summary: result.summary,
    ...(result.warning ? { warning: result.warning } : {}),
  });
});

// DELETE: cancel the in-flight upload.
export const DELETE = withAdmin(async (req, _ctx, _session) => {
  const uploadId = req.headers.get("x-upload-id") ?? "";
  if (!uploadId) {
    return NextResponse.json({ error: "Missing X-Upload-Id." }, { status: 400 });
  }
  await clearSession(uploadId);
  return NextResponse.json({ ok: true });
});
