import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Prisma client output — regenerated by `prisma generate` and never
    // hand-edited (CLAUDE.md guardrail 12). Mirrors the paths-ignore
    // already in .github/workflows/codeql.yml and trivy.yml.
    "src/generated/**",
  ]),
]);

export default eslintConfig;
