// Unit tests for src/lib/nav-items.ts — the last module in src/lib with no test
// of any kind, and the only one the suite could not previously even LOAD.
//
// Why it was unreachable: nav-items imports `@/components/icons`, a .ts barrel
// re-exporting ~100 .tsx files. Node's strip-only type stripping does not
// transform JSX, so the whole graph throws on parse. The fix here is local to
// this file rather than a change to tests/_loader.mjs: a resolve+load hook pair
// maps that one specifier to a synthetic module whose exports are GENERATED by
// reading the real barrel, so the stub can never drift out of sync with it. No
// other test imports icons, so widening the shared loader would have been a
// process-wide change to serve a single file.
//
// What is actually worth pinning here — nav-items looks like a plain data module,
// but three of its behaviours fail SILENTLY and invisibly to types:
//
//   1. FEATURE-FLAG WIRING IS BY STRING, IN BOTH DIRECTIONS. NAV_ITEM_FEATURE_KEY
//      maps href → flag key, and both sides are bare strings checked by nobody.
//      Rename an href and the entry goes dead; rename a flag in features.ts and
//      `flags[key]` reads undefined, which `!== false` treats as VISIBLE. Either
//      slip leaves an admin toggling a feature off while the nav entry stays up —
//      a fail-open, and the failure is invisible until someone tries the toggle.
//      Pinned in both directions against the real registry.
//   2. THE SAME FLAG GATES TWO ENTRIES. feature.page.issues covers /issues AND
//      /admin/issues, so disabling Issues must take both — a half-applied toggle
//      leaves a live entry into a disabled feature.
//   3. `exact` IS WHAT KEEPS "/" FROM MATCHING EVERYTHING. Drop it from Discover
//      and the sidebar highlights it on every route in the app.
//
// Also pinned: every nav href resolves to a real (app) page directory (a nav item
// pointing at a 404 is invisible to the compiler), and the permission tiers in
// getVisibleAdminItems — including its one genuine quirk, documented below, where
// an explicit `permissions: 0n` is falsy and silently falls back to the role.
//
// NOTE ON SCOPE: this is nav VISIBILITY, not authorization. getVisibleAdminItems
// decides what to draw; the actual gates are withAdmin/withPermission on the API
// routes and the DB-checked page reads (guardrails 6a/29). Hiding a link is not
// a security control and these tests do not treat it as one.
//
// No DB, no network — pure functions, the source files, and generated stubs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { registerHooks } from "node:module";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ICONS_BARREL = resolve(HERE, "../src/components/icons/index.ts");
const VIRTUAL_ICONS = "summonarr-test:icons";

// Generate the icon stub from the REAL barrel so it cannot drift: every
// `export { X } from "./x"` becomes a no-op component of the same name. The
// components are never rendered here — nav-items only holds references to them.
const iconNames = [...readFileSync(ICONS_BARREL, "utf8").matchAll(/export \{ (\w+) \} from/g)].map((m) => m[1]);
if (iconNames.length < 50) {
  throw new Error(`icon barrel parse produced only ${iconNames.length} names — the stub would be missing exports`);
}

registerHooks({
  resolve(specifier, context, nextResolve) {
    if (specifier === "@/components/icons") return { url: VIRTUAL_ICONS, shortCircuit: true };
    return nextResolve(specifier, context);
  },
  load(url, context, nextLoad) {
    if (url === VIRTUAL_ICONS) {
      return {
        format: "module",
        shortCircuit: true,
        source: iconNames.map((n) => `export const ${n} = () => null;`).join("\n"),
      };
    }
    return nextLoad(url, context);
  },
});

const {
  filterNavByFeatures,
  NAV_ITEM_FEATURE_KEY,
  userNavItems,
  adminNavItems,
  getVisibleAdminItems,
} = await import("../src/lib/nav-items.ts");
const { Permission } = await import("../src/lib/permissions.ts");

type NavLike = { href: string; label: string };
const ALL_ITEMS = [...userNavItems, ...adminNavItems];
const hrefs = (items: readonly { href: string }[]) => items.map((i) => i.href);

// ── the module loads at all ──────────────────────────────────────────────────

test("nav-items loads with real exports — a stub that resolved to nothing would pass every test below vacuously", () => {
  assert.ok(userNavItems.length >= 10, "user nav is suspiciously small");
  assert.ok(adminNavItems.length >= 8, "admin nav is suspiciously small");
  assert.equal(typeof filterNavByFeatures, "function");
  assert.equal(typeof getVisibleAdminItems, "function");
  // The icon references must be the generated stubs, not undefined: an import
  // that silently resolved to an empty namespace would leave every icon
  // undefined and still satisfy the shape assertions further down.
  for (const item of ALL_ITEMS) {
    assert.equal(typeof item.icon, "function", `${item.href} has no icon component`);
  }
});

// ── filterNavByFeatures ──────────────────────────────────────────────────────

test("undefined flags show everything — the fail-open the nav depends on when the flag query fails", () => {
  assert.deepEqual(hrefs(filterNavByFeatures(userNavItems, undefined)), hrefs(userNavItems));
});

test("undefined flags return a COPY, so a caller sorting the result can't reorder the module's nav", () => {
  const out = filterNavByFeatures(userNavItems, undefined);
  assert.notEqual(out, userNavItems as unknown);
  out.length = 0;
  assert.ok(userNavItems.length > 0, "the module array was emptied through the returned reference");
});

test("an empty flag map shows everything — 'no row stored yet' is not 'disabled'", () => {
  assert.deepEqual(hrefs(filterNavByFeatures(userNavItems, {})), hrefs(userNavItems));
});

test("an explicit false hides exactly that item and nothing else", () => {
  const out = filterNavByFeatures(userNavItems, { "feature.page.donate": false });
  assert.ok(!hrefs(out).includes("/donate"));
  assert.equal(out.length, userNavItems.length - 1);
});

test("an explicit true shows the item", () => {
  const out = filterNavByFeatures(userNavItems, { "feature.page.donate": true });
  assert.ok(hrefs(out).includes("/donate"));
});

test("a key absent from a POPULATED map still falls back to visible", () => {
  // The documented fail-open: only an explicit `false` hides. getFeatureFlags()
  // fills registered keys with defaults, so absence means an unregistered key.
  const out = filterNavByFeatures(userNavItems, { "feature.page.top": false });
  assert.ok(hrefs(out).includes("/donate"), "an unrelated unlisted flag hid an item");
});

test("an item with NO feature key is never hidden, whatever the map says", () => {
  const unmapped = userNavItems.filter((i) => !NAV_ITEM_FEATURE_KEY[i.href]);
  assert.ok(unmapped.length > 0, "expected some always-on nav items");
  const allFalse = Object.fromEntries(Object.values(NAV_ITEM_FEATURE_KEY).map((k) => [k, false]));
  const out = hrefs(filterNavByFeatures(userNavItems, allFalse));
  for (const item of unmapped) {
    assert.ok(out.includes(item.href), `${item.href} has no flag but was hidden`);
  }
});

test("turning every mapped flag off hides exactly the mapped subset", () => {
  const allFalse = Object.fromEntries(Object.values(NAV_ITEM_FEATURE_KEY).map((k) => [k, false]));
  const out = hrefs(filterNavByFeatures(ALL_ITEMS, allFalse));
  for (const href of Object.keys(NAV_ITEM_FEATURE_KEY)) {
    assert.ok(!out.includes(href), `${href} survived its flag being false`);
  }
  assert.ok(out.length > 0, "the whole nav vanished — that is not a filter, that is an outage");
});

test("a flag for an href that is not a nav item changes nothing", () => {
  const out = filterNavByFeatures(userNavItems, { "feature.page.nonexistent": false });
  assert.equal(out.length, userNavItems.length);
});

test("the input array is not mutated", () => {
  const before = hrefs(userNavItems);
  filterNavByFeatures(userNavItems, { "feature.page.donate": false });
  assert.deepEqual(hrefs(userNavItems), before);
});

test("it is generic over a bare {href} — the nav definition stays usable from both server and client", () => {
  const items: NavLike[] = [{ href: "/donate", label: "d" }, { href: "/profile", label: "p" }];
  const out = filterNavByFeatures(items, { "feature.page.donate": false });
  assert.deepEqual(out, [{ href: "/profile", label: "p" }]);
});

// ── flag-wiring drift, checked against the real registry ─────────────────────

const featuresSrc = readFileSync(resolve(HERE, "../src/lib/features.ts"), "utf8");
const registeredKeys = new Set([...featuresSrc.matchAll(/key: "([^"]+)"/g)].map((m) => m[1]));

test("the features registry parsed — an empty key set would make the next two tests vacuous", () => {
  assert.ok(registeredKeys.size >= 15, `only parsed ${registeredKeys.size} feature keys`);
});

test("every NAV_ITEM_FEATURE_KEY href is a real nav item — a dead entry silently un-gates a page", () => {
  const known = new Set(hrefs(ALL_ITEMS));
  for (const href of Object.keys(NAV_ITEM_FEATURE_KEY)) {
    assert.ok(known.has(href), `NAV_ITEM_FEATURE_KEY gates "${href}", which is not a nav item`);
  }
});

test("every NAV_ITEM_FEATURE_KEY flag is REGISTERED in features.ts — an unregistered key reads undefined, which shows the item", () => {
  for (const [href, key] of Object.entries(NAV_ITEM_FEATURE_KEY)) {
    assert.ok(
      registeredKeys.has(key),
      `${href} is gated on "${key}", which no longer exists in features.ts — the item can never be hidden`,
    );
  }
});

test("every feature.page.* flag is wired into the nav, except the documented non-nav one", () => {
  // forYou gates a section of the Discover page, not a nav destination.
  const NOT_A_NAV_DESTINATION = new Set(["feature.page.forYou"]);
  const wired = new Set(Object.values(NAV_ITEM_FEATURE_KEY));
  for (const key of registeredKeys) {
    if (!key.startsWith("feature.page.") || NOT_A_NAV_DESTINATION.has(key)) continue;
    assert.ok(wired.has(key), `${key} gates a page but no nav item is wired to it`);
  }
});

test("disabling Issues hides BOTH entries — the user one and the admin one share a flag", () => {
  const out = hrefs(filterNavByFeatures(ALL_ITEMS, { "feature.page.issues": false }));
  assert.ok(!out.includes("/issues"), "the user Issues entry survived");
  assert.ok(!out.includes("/admin/issues"), "the ADMIN Issues entry survived a disabled feature");
});

// ── getVisibleAdminItems: permission tiers ───────────────────────────────────

test("no argument yields no admin nav", () => {
  assert.deepEqual(getVisibleAdminItems(), []);
});

test("a plain USER gets no admin nav", () => {
  assert.deepEqual(getVisibleAdminItems("USER"), []);
});

test("an unrecognized role gets no admin nav", () => {
  assert.deepEqual(getVisibleAdminItems("SOMETHING_ELSE"), []);
});

test("the ADMIN role string gets the full admin nav", () => {
  assert.deepEqual(hrefs(getVisibleAdminItems("ADMIN")), hrefs(adminNavItems));
});

test("an object carrying role: ADMIN gets the full admin nav", () => {
  assert.deepEqual(hrefs(getVisibleAdminItems({ role: "ADMIN" })), hrefs(adminNavItems));
});

test("the ADMIN permission bit alone gets the full admin nav — no role needed", () => {
  assert.deepEqual(hrefs(getVisibleAdminItems({ permissions: Permission.ADMIN })), hrefs(adminNavItems));
});

test("permissions arriving as a STRING are parsed, not truthiness-tested", () => {
  // Session claims carry permissions as a decimal string (bigint is not JSON).
  assert.deepEqual(
    hrefs(getVisibleAdminItems({ permissions: Permission.ADMIN.toString() })),
    hrefs(adminNavItems),
  );
});

test("ISSUE_ADMIN sees ONLY the issues entry — not the users, backup or settings links", () => {
  const out = hrefs(getVisibleAdminItems("ISSUE_ADMIN"));
  assert.deepEqual(out, ["/admin/issues"]);
});

test("MANAGE_ISSUES alone sees only the issues entry", () => {
  const out = hrefs(getVisibleAdminItems({ permissions: Permission.MANAGE_ISSUES }));
  assert.deepEqual(out, ["/admin/issues"]);
});

test("MANAGE_USERS alone gets the full admin nav — the documented 'granular full-admin nav for now'", () => {
  assert.deepEqual(hrefs(getVisibleAdminItems({ permissions: Permission.MANAGE_USERS })), hrefs(adminNavItems));
});

test("MANAGE_REQUESTS alone gets the full admin nav", () => {
  assert.deepEqual(hrefs(getVisibleAdminItems({ permissions: Permission.MANAGE_REQUESTS })), hrefs(adminNavItems));
});

test("permissions outrank the role: a USER row carrying the ADMIN bit gets the admin nav", () => {
  assert.deepEqual(
    hrefs(getVisibleAdminItems({ role: "USER", permissions: Permission.ADMIN })),
    hrefs(adminNavItems),
  );
});

test("an explicit permissions: 0n falls back to the ROLE preset — 0n means 'never seeded', not 'no capabilities'", () => {
  // The codebase-wide convention, owned by effectivePermissions: a row whose mask
  // is literally zero predates the permissions migration (or a create site forgot
  // to seed it), so it resolves to the role preset rather than locking the user
  // out. A deliberately-restricted user has at least one bit set.
  assert.deepEqual(hrefs(getVisibleAdminItems({ role: "ADMIN", permissions: 0n })), hrefs(adminNavItems));
  assert.deepEqual(getVisibleAdminItems({ role: "USER", permissions: 0n }), []);
});

test("an ADMIN carrying non-zero, non-ADMIN bits still gets the admin nav — the role superbit is not dropped", () => {
  // The regression this function shipped with: resolution consulted the role only
  // when the mask was zero, so an ADMIN whose permissions had been hand-edited to
  // any other non-zero value resolved without Permission.ADMIN and got NOTHING.
  // effectivePermissions ORs the superbit in for role ADMIN at any mask.
  const out = getVisibleAdminItems({ role: "ADMIN", permissions: Permission.REQUEST });
  assert.deepEqual(hrefs(out), hrefs(adminNavItems), "a hand-edited ADMIN lost the entire admin nav");
});

test("a non-ADMIN role with a non-zero mask is still governed by the mask, not the preset", () => {
  // The other half of the convention, unchanged: a non-zero mask is authoritative
  // for every role except ADMIN, so restricting a user actually restricts them.
  assert.deepEqual(getVisibleAdminItems({ role: "USER", permissions: Permission.REQUEST }), []);
  assert.deepEqual(
    hrefs(getVisibleAdminItems({ role: "USER", permissions: Permission.MANAGE_ISSUES })),
    ["/admin/issues"],
  );
});

test('permissions "0" with no role yields nothing', () => {
  assert.deepEqual(getVisibleAdminItems({ permissions: "0" }), []);
});

test("the ISSUE_ADMIN filter returns a fresh array and leaves the module's admin nav intact", () => {
  const before = hrefs(adminNavItems);
  const out = getVisibleAdminItems("ISSUE_ADMIN");
  out.length = 0;
  assert.deepEqual(hrefs(adminNavItems), before);
});

// ── structural pins on the nav definitions ───────────────────────────────────

test("hrefs are unique across the whole nav", () => {
  const seen = hrefs(ALL_ITEMS);
  assert.equal(new Set(seen).size, seen.length, `duplicate href: ${seen.filter((h, i) => seen.indexOf(h) !== i)}`);
});

test("every item has a label, an icon and an absolute href", () => {
  for (const item of ALL_ITEMS) {
    assert.ok(item.label.trim().length > 0, `${item.href} has no label`);
    assert.ok(item.icon, `${item.href} has no icon`);
    assert.ok(item.href.startsWith("/"), `${item.href} is not absolute`);
    assert.ok(item.href === "/" || !item.href.endsWith("/"), `${item.href} has a trailing slash`);
  }
});

test("every admin item is section 'admin'; user items are browse or personal", () => {
  for (const item of adminNavItems) assert.equal(item.section, "admin", `${item.href} is misfiled`);
  for (const item of userNavItems) {
    assert.ok(["browse", "personal"].includes(item.section), `${item.href} is section ${item.section}`);
  }
});

test("`exact` is set on exactly the two ROOT hrefs — without it they match every nested route", () => {
  // "/" is a prefix of every path in the app, and "/admin" of every admin path,
  // so a non-exact match highlights Discover (or Requested) on every page.
  const exact = ALL_ITEMS.filter((i) => i.exact).map((i) => i.href).sort();
  assert.deepEqual(exact, ["/", "/admin"]);
});

test("the mobile bottom bar holds at most 5 items, all from the user nav", () => {
  const bar = ALL_ITEMS.filter((i) => i.mobileBottomBar);
  assert.ok(bar.length > 0 && bar.length <= 5, `bottom bar has ${bar.length} items`);
  for (const item of bar) {
    assert.ok(userNavItems.includes(item), `${item.href} is in the bottom bar but not the user nav`);
  }
});

test("every admin nav href is under /admin, or is the settings page", () => {
  for (const item of adminNavItems) {
    assert.ok(
      item.href.startsWith("/admin") || item.href === "/settings",
      `${item.href} is in the admin nav but outside the admin surface`,
    );
  }
});

test("every nav href resolves to a real (app) page — a link to a 404 is invisible to the compiler", () => {
  const appDir = resolve(HERE, "../src/app/(app)");
  for (const item of ALL_ITEMS) {
    const page = item.href === "/"
      ? resolve(appDir, "page.tsx")
      : resolve(appDir, `.${item.href}`, "page.tsx");
    assert.ok(existsSync(page), `${item.href} points at a page that does not exist (${page})`);
  }
});
