import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { sanitizeText } from "@/lib/sanitize";
import { checkRateLimit, getClientIp } from "@/lib/rate-limit";
import { checkBodySize } from "@/lib/body-size";
import {
  processBackupImport,
  MAX_CIPHERTEXT_BYTES,
} from "@/lib/backup-import";
import {
  startSession,
  appendChunk,
  getSessionStream,
  clearSession,
} from "@/lib/import-session";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const MIN_BACKUP_PASSWORD_LEN = 12;
// Client uploader defaults to 16 MiB chunks; cap at 32 MiB to leave headroom while still bounding memory.
const MAX_CHUNK_BYTES = 32 * 1024 * 1024;

async function gate(): Promise<NextResponse | { password: string } | { closed: true }> {
  // Advisory lock 43 is shared with /api/auth/register and /api/setup/import. Mirroring the
  // setup/import gate guarantees a racing register can't sneak between the freshness check and
  // the eventual processBackupImport on the final chunk. processBackupImport re-takes the lock
  // and re-checks the invariant for full safety; this gate provides fast-fail UX so a chunked
  // uploader doesn't buffer hundreds of megabytes against an already-set-up server.
  const closed = await prisma.$transaction(async (tx) => {
    await tx.$executeRawUnsafe("SELECT pg_advisory_xact_lock(43)");
    const setupCompleted = await tx.setting.findUnique({ where: { key: "setup_completed_at" } });
    const userCount = await tx.user.count();
    return setupCompleted !== null || userCount > 0;
  });
  if (closed) {
    // Signalled distinctly so the caller can release the single global upload
    // slot for this uploadId. Otherwise an in-flight session keeps the slot
    // pinned until its TTL when a legitimate admin completes setup mid-upload.
    return { closed: true };
  }
  const password = process.env.BACKUP_DB_PASSWORD ?? "";
  if (password.length === 0) {
    return NextResponse.json(
      { error: "Backup is not configured. Set the BACKUP_DB_PASSWORD environment variable on the server." },
      { status: 503 },
    );
  }
  if (password.length < MIN_BACKUP_PASSWORD_LEN) {
    return NextResponse.json(
      { error: `BACKUP_DB_PASSWORD is too short (minimum ${MIN_BACKUP_PASSWORD_LEN} characters).` },
      { status: 503 },
    );
  }
  return { password };
}

// POST: append a chunk. On the final chunk, run the import.
//
// Headers:
//   X-Upload-Id     UUID v4 generated by the client
//   X-Chunk-Index   0-based index of this chunk
//   X-Chunk-Total   total chunks in the upload
//   X-File-Size     total file size in bytes
// Body: raw chunk bytes (application/octet-stream)
export async function POST(req: NextRequest) {
  const uploadId = req.headers.get("x-upload-id") ?? "";
  const chunkIndex = Number(req.headers.get("x-chunk-index") ?? "");
  const chunkTotal = Number(req.headers.get("x-chunk-total") ?? "");
  const fileSize = Number(req.headers.get("x-file-size") ?? "");

  if (!uploadId || !Number.isFinite(chunkIndex) || !Number.isFinite(chunkTotal) || !Number.isFinite(fileSize)) {
    return NextResponse.json({ error: "Missing or invalid upload headers." }, { status: 400 });
  }

  // Rate-limit the upload *attempt*, not each chunk: consume one slot when the client
  // opens the session (chunk 0). A real backup is split into many 16 MiB chunks, so a
  // per-chunk limiter would burn the whole bucket and 429 the restore partway through.
  if (chunkIndex === 0 && !checkRateLimit(`setup-import:${getClientIp(req.headers)}`, 5, 5 * 60 * 1000)) {
    return NextResponse.json({ error: "Too many setup-import attempts. Try again later." }, { status: 429 });
  }

  const sizeCheck = checkBodySize(req, MAX_CHUNK_BYTES);
  if (sizeCheck) return sizeCheck;

  const g = await gate();
  if (g instanceof NextResponse) return g;
  if ("closed" in g) {
    // Setup completed (or a user appeared) mid-upload. Free the single global
    // slot this uploadId holds so a subsequent legitimate restore isn't blocked
    // by a stale in-flight session until its TTL.
    await clearSession(uploadId);
    return NextResponse.json(
      { error: "Setup import is only available on a fresh server with no users." },
      { status: 409 },
    );
  }
  const { password } = g;

  if (fileSize > MAX_CIPHERTEXT_BYTES) {
    return NextResponse.json(
      { error: `File exceeds the ${Math.round(MAX_CIPHERTEXT_BYTES / (1024 * 1024))} MB limit.` },
      { status: 413 },
    );
  }

  if (chunkIndex === 0) {
    const start = await startSession({ uploadId, totalSize: fileSize, totalChunks: chunkTotal });
    if (!start.ok) {
      const e = start.error;
      if (e.kind === "in-progress") {
        return NextResponse.json(
          { error: "Another upload is already in progress. Wait for it to finish or cancel it." },
          { status: 409 },
        );
      }
      if (e.kind === "size-too-large") {
        return NextResponse.json(
          { error: `File exceeds the ${Math.round(e.max / (1024 * 1024))} MB limit.` },
          { status: 413 },
        );
      }
      return NextResponse.json({ error: "Invalid upload parameters." }, { status: 400 });
    }
  }

  if (!req.body) {
    return NextResponse.json({ error: "Empty chunk body." }, { status: 400 });
  }

  const chunkBytes = new Uint8Array(await req.arrayBuffer());
  // Post-read cap for Transfer-Encoding: chunked uploads, where checkBodySize's
  // Content-Length check above can't fire (mirrors db-import-chunk). Release the
  // slot claimed on chunk 0 so an oversized first chunk doesn't strand the
  // uploader for the session TTL.
  if (chunkBytes.byteLength > MAX_CHUNK_BYTES) {
    // An oversized chunk corrupts the upload — release the slot for ANY index
    // (not just chunk 0) so it isn't stranded until the session TTL.
    await clearSession(uploadId);
    return NextResponse.json(
      { error: `Chunk exceeds ${Math.round(MAX_CHUNK_BYTES / (1024 * 1024))} MB cap.` },
      { status: 413 },
    );
  }
  const append = await appendChunk(uploadId, chunkIndex, chunkBytes);
  if (!append.ok) {
    const e = append.error;
    if (e.kind === "no-session") {
      return NextResponse.json({ error: "No active upload session — start at chunk 0." }, { status: 409 });
    }
    if (e.kind === "session-mismatch") {
      return NextResponse.json({ error: "Upload-id does not match the active session." }, { status: 409 });
    }
    if (e.kind === "expired") {
      return NextResponse.json({ error: "Upload session expired — restart from chunk 0." }, { status: 410 });
    }
    if (e.kind === "out-of-order") {
      return NextResponse.json({ error: `Out-of-order chunk. Next expected index: ${e.expected}.` }, { status: 409 });
    }
    if (e.kind === "size-mismatch") {
      return NextResponse.json(
        { error: `Upload incomplete: received ${e.received} of ${e.expected} declared bytes. Restart from chunk 0.` },
        { status: 400 },
      );
    }
    return NextResponse.json({ error: "Chunk exceeds declared file size." }, { status: 413 });
  }

  if (!append.complete) {
    return NextResponse.json({
      ok: true,
      received: append.received,
      total: append.total,
      bytesWritten: append.bytesWritten,
      complete: false,
    });
  }

  const stream = getSessionStream(uploadId);
  if (!stream) {
    await clearSession(uploadId);
    return NextResponse.json({ error: "Upload state lost between final chunk and import." }, { status: 500 });
  }

  let result;
  try {
    result = await processBackupImport(stream, password, "setup");
  } finally {
    await clearSession(uploadId);
  }

  if (!result.ok) {
    if (result.errors) {
      return NextResponse.json({
        ok: false,
        complete: true,
        summary: result.summary,
        errors: result.errors,
      });
    }
    return NextResponse.json({ error: result.error, complete: true }, { status: result.status });
  }

  try {
    await prisma.auditLog.create({
      data: {
        userId: null,
        userName: "system (setup)",
        action: "BACKUP_IMPORT",
        target: "backup:full-db",
        details: JSON.stringify({
          format: "sql",
          encrypted: true,
          mode: "setup-chunked",
          after: {
            totalStatements: result.summary.total,
            executed: result.summary.executed,
            skipped: result.summary.skipped,
            errors: result.summary.errors,
          },
        }),
        ipAddress: getClientIp(req.headers),
        userAgent: sanitizeText(req.headers.get("user-agent")?.slice(0, 512) ?? ""),
      },
    });
  } catch (err) {
    console.error("[audit] Setup-import audit log failed:", err);
  }

  return NextResponse.json({
    ok: true,
    complete: true,
    summary: result.summary,
    ...(result.warning ? { warning: result.warning } : {}),
  });
}

// DELETE: cancel the in-flight upload and remove the temp file.
export async function DELETE(req: NextRequest) {
  const uploadId = req.headers.get("x-upload-id") ?? "";
  if (!uploadId) {
    return NextResponse.json({ error: "Missing X-Upload-Id." }, { status: 400 });
  }
  // Cancel only releases the in-memory upload slot + temp file for this
  // uploadId (no DB mutation), and clearSession is a no-op unless this uploadId
  // owns the active session. It must always succeed so a stale slot can be
  // freed even after setup has closed or backup config changed.
  await clearSession(uploadId);
  return NextResponse.json({ ok: true });
}
